# Task 2: SQL for Data Analysis
**Internship:** ApexPlanet Software Pvt. Ltd.

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine("sqlite:///../sales.db")

In [4]:
df = pd.read_sql("SELECT * FROM sales_data", engine)
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

## Query 1: Display First 10 Records

Retrieve the first 10 records from the `sales_data` table.

In [8]:
query = "SELECT * FROM sales_data LIMIT 10;"
pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656
5,9,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-BI-10003910,Office Supplies,Binders,DXL Angle-View Binders with Locking Rings by S...,18.504,3,0.2,5.7825
6,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
7,13,CA-2017-114412,2017-04-15,2017-04-20,Standard Class,AA-10480,Andrew Allen,Consumer,United States,Concord,...,28027,South,OFF-PA-10002365,Office Supplies,Paper,Xerox 1967,15.552,3,0.2,5.4432
8,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,0.2,132.5922
9,15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580

## Query 2: Filter Sales Greater Than 300

Retrieve all records where the sales value is greater than 300.

In [9]:
query = """
SELECT *
FROM sales_data
WHERE Sales > 300;
"""
pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922
1,41,CA-2015-117415,2015-12-27,2015-12-31,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,371.1680,4,0.20,41.7564
2,58,CA-2016-111682,2016-06-17,2016-06-18,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,...,12180,East,FUR-CH-10003968,Furniture,Chairs,Novimex Turbo Task Chair,319.4100,5,0.10,7.0980
3,86,CA-2017-140088,2017-05-28,2017-05-30,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Columbia,...,29203,South,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,301.9600,2,0.00,33.2156
4,110,CA-2015-129476,2015-10-15,2015-10-20,Standard Class,PA-19060,Pete Armstrong,Home Office,United States,Orland Park,...,60462,Central,TEC-AC-10000844,Technology,Accessories,Logitech Gaming G510s - Keyboard,339.9600,5,0.20,67.9920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,9898,CA-2016-112830,2016-06-06,2016-06-10,Standard Class,LP-17095,Liz Preis,Consumer,United States,Fairfield,...,45014,East,FUR-FU-10004306,Furniture,Furnishings,Electrix Halogen Magnifier Lamp,466.3200,3,0.20,34.9740
733,9900,US-2014-117380,2014-03-28,2014-04-03,Standard Class,MP-18175,Mike Pelletier,Home Office,United States,Springfield,...,45503,East,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,330.5880,1,0.40,-143.2548
734,9913,CA-2015-132388,2015-10-10,2015-10-12,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,...,93101,West,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",362.1360,3,0.20,-54.3204
735,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
736,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152

## Query 3: Total Sales by Category

Calculate the total sales for each product category using the `GROUP BY` clause.

In [10]:
query = """
SELECT Category,
       SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY Category;
"""
pd.read_sql(query, engine)

          Category  Total_Sales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

## Query 4: Top 10 Highest Sales

Display the top 10 transactions with the highest sales values.

In [11]:
query = """
SELECT *
FROM sales_data
ORDER BY Sales DESC;
"""
pd.read_sql(query, engine).head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,5220,CA-2017-145653,2017-09-01,2017-09-01,Same Day,CA-12775,Cynthia Arntzen,Consumer,United States,Detroit,...,48205,Central,FUR-CH-10004875,Furniture,Chairs,Harbour Creations 67200 Series Stacking Chairs,498.260,7,0.0,134.5302
1,8339,CA-2014-153087,2014-12-27,2015-01-03,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Decatur,...,35601,South,TEC-AC-10003198,Technology,Accessories,Enermax Acrylux Wireless Keyboard,498.000,5,0.0,184.2600
2,7558,CA-2017-159506,2017-11-27,2017-12-02,Standard Class,JR-16210,Justin Ritter,Corporate,United States,Columbus,...,47201,Central,OFF-BI-10004519,Office Supplies,Binders,GBC DocuBind P100 Manual Binding Machine,497.940,3,0.0,224.0730
3,1775,CA-2014-118976,2014-04-28,2014-05-03,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Baltimore,...,21215,East,OFF-ST-10000877,Office Supplies,Storage,Recycled Steel Personal File for Standard File...,497.610,9,0.0,129.3786
4,8533,CA-2016-156748,2016-11-30,2016-12-06,Standard Class,BS-11755,Bruce Stewart,Consumer,United States,Detroit,...,48227,Central,OFF-ST-10001370,Office Supplies,Storage,Sensible Storage WireTech Storage Systems,496.860,7,0.0,24.8430
5,2242,US-2016-126893,2016-11-26,2016-12-01,Standard Class,CT-11995,Carol Triggs,Consumer,United States,Philadelphia,...,19134,East,TEC-PH-10004165,Technology,Phones,Mitel MiVoice 5330e IP Phone,494.982,3,0.4,-115.4958
6,6854,US-2017-162670,2017-12-23,2017-12-28,Second Class,MF-18250,Monica Federle,Corporate,United States,Little Rock,...,72209,South,TEC-PH-10003601,Technology,Phones,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970,3,0.0,148.4910
7,8899,CA-2015-163237,2015-08-07,2015-08-09,Second Class,EM-14095,Eudokia Martin,Corporate,United States,Springfield,...,22153,South,TEC-PH-10003601,Technology,Phones,Ativa D5772 2-Line 5.8GHz Digital Expandable C...,494.970,3,0.0,148.4910
8,601,US-2016-100720,2016-07-16,2016-07-21,Standard Class,CK-12205,Chloris Kastensmidt,Consumer,United States,Philadelphia,...,19120,East,TEC-PH-10003963,Technology,Phones,GE 2-Jack Phone Line Splitter,494.376,4,0.4,-115.3544
9,3288,CA-2015-157770,2015-12-13,2015-12-15,First Class,RD-19585,Rob Dowd,Consumer,United States,Temecula,...,92592,West,TEC-PH-10001530,Technology,Phones,Plantronics Voyager Pro Legend,494.376,3,0.2,49.4376

## Query 5: Aggregate Statistics

Calculate the total number of orders, total sales, average sales, maximum sales, and minimum sales.

In [12]:
query = """
SELECT
COUNT(*) AS Total_Orders,
SUM(Sales) AS Total_Sales,
AVG(Sales) AS Average_Sales,
MAX(Sales) AS Highest_Sale,
MIN(Sales) AS Lowest_Sale
FROM sales_data;
"""
pd.read_sql(query, engine)

   Total_Orders  Total_Sales  Average_Sales  Highest_Sale  Lowest_Sale
0          8827  819718.0554      92.864853        498.26        0.444

## Query 6: Display High Sales View

Retrieve all records from the SQL view `High_Sales`.

In [13]:
query = "SELECT * FROM High_Sales;"
pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922
1,41,CA-2015-117415,2015-12-27,2015-12-31,Standard Class,SN-20710,Steve Nguyen,Home Office,United States,Houston,...,77041,Central,TEC-PH-10000486,Technology,Phones,Plantronics HL10 Handset Lifter,371.1680,4,0.20,41.7564
2,58,CA-2016-111682,2016-06-17,2016-06-18,First Class,TB-21055,Ted Butterfield,Consumer,United States,Troy,...,12180,East,FUR-CH-10003968,Furniture,Chairs,Novimex Turbo Task Chair,319.4100,5,0.10,7.0980
3,86,CA-2017-140088,2017-05-28,2017-05-30,Second Class,PO-18865,Patrick O'Donnell,Consumer,United States,Columbia,...,29203,South,FUR-CH-10000863,Furniture,Chairs,Novimex Swivel Fabric Task Chair,301.9600,2,0.00,33.2156
4,110,CA-2015-129476,2015-10-15,2015-10-20,Standard Class,PA-19060,Pete Armstrong,Home Office,United States,Orland Park,...,60462,Central,TEC-AC-10000844,Technology,Accessories,Logitech Gaming G510s - Keyboard,339.9600,5,0.20,67.9920
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
732,9898,CA-2016-112830,2016-06-06,2016-06-10,Standard Class,LP-17095,Liz Preis,Consumer,United States,Fairfield,...,45014,East,FUR-FU-10004306,Furniture,Furnishings,Electrix Halogen Magnifier Lamp,466.3200,3,0.20,34.9740
733,9900,US-2014-117380,2014-03-28,2014-04-03,Standard Class,MP-18175,Mike Pelletier,Home Office,United States,Springfield,...,45503,East,FUR-TA-10000198,Furniture,Tables,Chromcraft Bull-Nose Wood Oval Conference Tabl...,330.5880,1,0.40,-143.2548
734,9913,CA-2015-132388,2015-10-10,2015-10-12,First Class,KN-16390,Katherine Nockton,Corporate,United States,Santa Barbara,...,93101,West,FUR-CH-10001714,Furniture,Chairs,"Global Leather & Oak Executive Chair, Burgundy",362.1360,3,0.20,-54.3204
735,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,77041,Central,FUR-BO-10004218,Furniture,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704
736,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.4720,14,0.20,153.1152

In [2]:
import pandas as pd
from sqlalchemy import create_engine

In [3]:
engine = create_engine("sqlite:///../sales.db")

## Query 7: INNER JOIN

Join two tables to combine category and department information.

In [4]:
query = """
SELECT
    s.Category,
    c.Department,
    s.Sales
FROM sales_data s
INNER JOIN category_info c
ON s.Category = c.Category
LIMIT 10;
"""

pd.read_sql(query, engine)

          Category Department    Sales
0        Furniture       Home  261.960
1  Office Supplies     Office   14.620
2  Office Supplies     Office   22.368
3        Furniture       Home   48.860
4  Office Supplies     Office    7.280
5  Office Supplies     Office   18.504
6  Office Supplies     Office  114.900
7  Office Supplies     Office   15.552
8  Office Supplies     Office  407.976
9  Office Supplies     Office   68.810

## Query 8: Subquery

Retrieve records having sales greater than the average sales.

In [5]:
query = """
SELECT *
FROM sales_data
WHERE Sales >
(
    SELECT AVG(Sales)
    FROM sales_data
);
"""

pd.read_sql(query, engine)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,10,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.900,5,0.0,34.4700
2,14,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.976,3,0.2,132.5922
3,20,CA-2014-143336,2014-08-27,2014-09-01,Second Class,ZD-21925,Zuschuss Donatelli,Consumer,United States,San Francisco,...,94109,West,TEC-PH-10001949,Technology,Phones,Cisco SPA 501G IP Phone,213.480,3,0.2,16.0110
4,30,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,FUR-FU-10004848,Furniture,Furnishings,"Howard Miller 13-3/4"" Diameter Brushed Chrome ...",124.200,3,0.2,15.5250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2753,9980,US-2016-103674,2016-12-06,2016-12-10,Standard Class,AP-10720,Anne Pryor,Home Office,United States,Los Angeles,...,90032,West,OFF-BI-10002026,Office Supplies,Binders,Ibico Recycled Linen-Style Covers,437.472,14,0.2,153.1152
2754,9984,US-2016-157728,2016-09-22,2016-09-28,Standard Class,RC-19960,Ryan Crowe,Consumer,United States,Grand Rapids,...,49505,Central,TEC-PH-10001305,Technology,Phones,Panasonic KX TS208W Corded phone,97.980,2,0.0,27.4344
2755,9989,CA-2017-163629,2017-11-17,2017-11-21,Standard Class,RA-19885,Ruben Ausman,Corporate,United States,Athens,...,30605,South,TEC-PH-10004006,Technology,Phones,Panasonic KX - TS880B Telephone,206.100,5,0.0,55.6470
2756,9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
2757,9994,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

## Query 9: Common Table Expression (CTE)

Calculate total sales for each category using the WITH clause.

In [6]:
query = """
WITH CategorySales AS
(
    SELECT
        Category,
        SUM(Sales) AS TotalSales
    FROM sales_data
    GROUP BY Category
)

SELECT *
FROM CategorySales;
"""

pd.read_sql(query, engine)

          Category   TotalSales
0        Furniture  247877.6984
1  Office Supplies  343425.0040
2       Technology  228415.3530

## Query 10: ROW_NUMBER()

Assign row numbers to sales records within each category.

In [7]:
query = """
SELECT
Category,
Sales,
ROW_NUMBER() OVER
(
PARTITION BY Category
ORDER BY Sales DESC
) AS Row_Number
FROM sales_data;
"""

pd.read_sql(query, engine)

        Category    Sales  Row_Number
0      Furniture  498.260           1
1      Furniture  493.920           2
2      Furniture  493.430           3
3      Furniture  492.835           4
4      Furniture  489.230           5
...          ...      ...         ...
8822  Technology    2.376        1443
8823  Technology    1.980        1444
8824  Technology    1.980        1445
8825  Technology    1.584        1446
8826  Technology    0.990        1447

[8827 rows x 3 columns]

## Query 11: RANK()

Rank sales within each category.

In [8]:
query = """
SELECT
Category,
Sales,
RANK() OVER
(
PARTITION BY Category
ORDER BY Sales DESC
) AS Sales_Rank
FROM sales_data;
"""

pd.read_sql(query, engine)

        Category    Sales  Sales_Rank
0      Furniture  498.260           1
1      Furniture  493.920           2
2      Furniture  493.430           3
3      Furniture  492.835           4
4      Furniture  489.230           5
...          ...      ...         ...
8822  Technology    2.376        1442
8823  Technology    1.980        1444
8824  Technology    1.980        1444
8825  Technology    1.584        1446
8826  Technology    0.990        1447

[8827 rows x 3 columns]

## Query 12: LAG()

Display previous sales value.

In [9]:
query = """
SELECT
"Order Date",
Sales,
LAG(Sales) OVER
(
ORDER BY "Order Date"
) AS Previous_Sales
FROM sales_data;
"""

pd.read_sql(query, engine)

      Order Date    Sales  Previous_Sales
0     2014-01-03   16.448             NaN
1     2014-01-04   11.784          16.448
2     2014-01-04  272.736          11.784
3     2014-01-04    3.540         272.736
4     2014-01-05   19.536           3.540
...          ...      ...             ...
8822  2017-12-30   90.930         323.136
8823  2017-12-30   52.776          90.930
8824  2017-12-30   13.904          52.776
8825  2017-12-30   20.720          13.904
8826  2017-12-30    3.024          20.720

[8827 rows x 3 columns]

## Query 13: LEAD()

Display next sales value.

In [10]:
query = """
SELECT
"Order Date",
Sales,
LEAD(Sales) OVER
(
ORDER BY "Order Date"
) AS Next_Sales
FROM sales_data;
"""

pd.read_sql(query, engine)

      Order Date    Sales  Next_Sales
0     2014-01-03   16.448      11.784
1     2014-01-04   11.784     272.736
2     2014-01-04  272.736       3.540
3     2014-01-04    3.540      19.536
4     2014-01-05   19.536      19.440
...          ...      ...         ...
8822  2017-12-30   90.930      52.776
8823  2017-12-30   52.776      13.904
8824  2017-12-30   13.904      20.720
8825  2017-12-30   20.720       3.024
8826  2017-12-30    3.024         NaN

[8827 rows x 3 columns]

# Conclusion

- Imported the cleaned dataset into SQLite.
- Executed SQL queries for data extraction.
- Performed filtering, sorting, grouping, and aggregation.
- Created reusable SQL views.
- Used JOINs to combine tables.
- Implemented subqueries and Common Table Expressions (CTEs).
- Applied window functions including ROW_NUMBER(), RANK(), LAG(), and LEAD().
- Connected SQLite with Python using SQLAlchemy and executed SQL queries using Pandas.

In [13]:
import sys
from pathlib import Path

# Add the project root to Python's path
project_root = Path.cwd().parent
sys.path.append(str(project_root))

In [14]:
from scripts.database_utils import run_query

In [15]:
query = "SELECT * FROM sales_data LIMIT 5;"
run_query(query)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.960,2,0.0,41.9136
1,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.620,2,0.0,6.8714
2,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.368,2,0.2,2.5164
3,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-FU-10001487,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,48.860,7,0.0,14.1694
4,7,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AR-10002833,Office Supplies,Art,Newell 322,7.280,4,0.0,1.9656

## Business Question 1: What are the top 5 products by total sales?

This query identifies the five products that generated the highest total sales.

In [16]:
query = """
SELECT
    "Product Name",
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 5;
"""

run_query(query)

                                       Product Name  Total_Sales
0                        KI Adjustable-Height Table     4036.761
1   Global Wood Trimmed Manager's Task Chair, Khaki     3621.004
2        Situations Contoured Folding Chairs, 4/Set     2959.866
3         Global High-Back Leather Tilter, Burgundy     2841.069
4  Nortel Meridian M3904 Professional Digital phone     2802.618

## Business Question 2: What is the monthly sales trend?

This query analyzes monthly sales to identify trends over time.

In [17]:
query = """
SELECT
    strftime('%Y-%m', "Order Date") AS Month,
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY Month
ORDER BY Month;
"""

run_query(query)

      Month  Total_Sales
0   2014-01    5438.1550
1   2014-02    3263.6720
2   2014-03   12452.5360
3   2014-04   11421.1910
4   2014-05   10456.7150
5   2014-06   10510.3486
6   2014-07   11024.2770
7   2014-08   12954.6225
8   2014-09   20696.5088
9   2014-10   13696.0970
10  2014-11   22934.5397
11  2014-12   23771.2075
12  2015-01    5594.0340
13  2015-02    5063.5290
14  2015-03   10771.9416
15  2015-04   13167.9905
16  2015-05   10807.4140
17  2015-06   10842.2570
18  2015-07   13015.7570
19  2015-08   12552.8122
20  2015-09   20435.1800
21  2015-10   15397.4880
22  2015-11   27483.3603
23  2015-12   27471.5480
24  2016-01    8508.9570
25  2016-02    9152.2500
26  2016-03   15162.3320
27  2016-04   12776.6920
28  2016-05   16370.4500
29  2016-06   18361.5700
30  2016-07   16262.3720
31  2016-08   13239.3678
32  2016-09   28732.5435
33  2016-10   15377.2050
34  2016-11   30624.2540
35  2016-12   31389.2940
36  2017-01   12369.8630
37  2017-02   10470.4194
38  2017-03   21964.4808
39  2017-04   15790.3786
40  2017-05   20387.3354
41  2017-06   21350.8592
42  2017-07   20725.4830
43  2017-08   17624.2220
44  2017-09   37662.6420
45  2017-10   21863.2602
46  2017-11   36791.9560
47  2017-12   35536.6868

## Business Question 3: Which customers spend the most?

This query ranks customers based on their total spending.

In [18]:
query = """
SELECT
    "Customer Name",
    SUM(Sales) AS Total_Spent
FROM sales_data
GROUP BY "Customer Name"
ORDER BY Total_Spent DESC
LIMIT 10;
"""

run_query(query)

     Customer Name  Total_Spent
0       Paul Prost    4196.9280
1  Laura Armstrong    3751.7980
2     Ken Lonsdale    3371.6910
3         John Lee    3338.3520
4    William Brown    3131.9740
5     Noel Staavos    2964.8230
6      Rick Wilson    2879.8910
7    Sally Hughsby    2865.5995
8     Edward Hooks    2821.2100
9    Arthur Gainer    2806.8510

## Business Question 4: Which category generates the highest total sales?

This query calculates the total sales for each product category and ranks them in descending order.

In [19]:
query = """
SELECT
    Category,
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

run_query(query)

          Category  Total_Sales
0  Office Supplies  343425.0040
1        Furniture  247877.6984
2       Technology  228415.3530

## Business Question 5: Which region contributes the highest total sales?

This query identifies the regions with the highest sales.

In [20]:
query = """
SELECT
    State,
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

run_query(query)

          State  Total_Sales
0    California  175475.7375
1      New York   92379.4070
2         Texas   71672.9344
3  Pennsylvania   45628.6270
4    Washington   41245.3560
5          Ohio   37495.3080
6      Illinois   36821.0430
7       Florida   27593.4735
8      Michigan   25737.0760
9       Arizona   20945.1490

## Business Question 6: Which states have the highest total sales?

This query calculates total sales for each state.

In [21]:
query = """
SELECT
    State,
    SUM(Sales) AS Total_Sales
FROM sales_data
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

run_query(query)

          State  Total_Sales
0    California  175475.7375
1      New York   92379.4070
2         Texas   71672.9344
3  Pennsylvania   45628.6270
4    Washington   41245.3560
5          Ohio   37495.3080
6      Illinois   36821.0430
7       Florida   27593.4735
8      Michigan   25737.0760
9       Arizona   20945.1490

## Business Question 7: Which products generate the highest profit?

This query identifies the top 10 most profitable products.

In [22]:
query = """
SELECT
    "Product Name",
    SUM(Profit) AS Total_Profit
FROM sales_data
GROUP BY "Product Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

run_query(query)

                                        Product Name  Total_Profit
0                                  Easy-staple paper     1096.0292
1  Dot Matrix Printer Tape Reel Labels, White, 50...      904.4520
2                                         Xerox 1908      799.3944
3                                         Xerox 1945      756.2655
4                                    Staple envelope      751.6290
5                                          Xerox 189      746.5320
6                                         Xerox 1919      729.6220
7                       Enermax Aurora Lite Keyboard      722.1060
8                   Logitech Gaming G510s - Keyboard      676.5204
9  GE 48" Fluorescent Tube, Cool White Energy Sav...      664.8410

## Business Question 8: What is the average profit for each category?

This query calculates the average profit earned by each product category.

In [23]:
query = """
SELECT
    Category,
    AVG(Profit) AS Average_Profit
FROM sales_data
GROUP BY Category;
"""

run_query(query)

          Category  Average_Profit
0        Furniture       -1.641194
1  Office Supplies       11.557726
2       Technology       24.454336

## Business Question 9: Which products received the highest discount?

This query lists products with the highest discount values.

In [24]:
query = """
SELECT
    "Product Name",
    Discount
FROM sales_data
ORDER BY Discount DESC
LIMIT 10;
"""

run_query(query)

                                        Product Name  Discount
0  Holmes Replacement Filter for HEPA Air Cleaner...       0.8
1   Storex DuraTech Recycled Plastic Frosted Binders       0.8
2                                    Economy Binders       0.8
3      Avery Hidden Tab Dividers for Binding Systems       0.8
4       Kensington 7 Outlet MasterPiece Power Center       0.8
5  Kensington 7 Outlet MasterPiece HOMEOFFICE Pow...       0.8
6  Acco 7-Outlet Masterpiece Power Center, Wihtou...       0.8
7               Eureka Sanitaire  Commercial Upright       0.8
8  Eureka Disposable Bags for Sanitaire Vibra Gro...       0.8
9                                 Round Ring Binders       0.8

## Business Question 10: Which customers generate the highest profit?

This query identifies customers who contributed the highest total profit.

In [25]:
query = """
SELECT
    "Customer Name",
    SUM(Profit) AS Total_Profit
FROM sales_data
GROUP BY "Customer Name"
ORDER BY Total_Profit DESC
LIMIT 10;
"""

run_query(query)

          Customer Name  Total_Profit
0       Laura Armstrong     1074.2069
1            Paul Prost      897.8652
2              John Lee      785.2348
3          Edward Hooks      782.4188
4  Christine Sundaresam      720.3522
5        Roland Schwarz      708.2743
6   Marina Lichtenstein      684.9162
7     Elizabeth Moffitt      682.5542
8          Matt Abelman      657.6438
9       Damala Kotsonis      654.1584

# Conclusion

In this task, SQL was used to answer business-oriented questions based on the Superstore Sales dataset. The analysis identified top-performing products, customers, regions, and categories, while also examining sales trends, profits, and discounts. By combining SQL with Python and SQLite, meaningful business insights were extracted to support data-driven decision-making.